class Usuario {
  late String nome;
  late String login;
  late String senha;
  late String email;
  late String telefone;
  late String endereco;
  late String cidade;
  late String estado;
  late String cep;
  late String bairro;
  late String foto;
  late String tipoUsuario;
  late String status;
  late DateTime dataNascimento;
  late DateTime dataCadastro;
  late DateTime dataAlteracao;
  late DateTime dataExclusao;
}
